### ISSUE TITLE
E492: Not an editor command: Dashboard

### ISSUE THREAD

**Issue by rossvz** [artart222/CodeArt#17]
Testing on macOS

After running the `install.py` command, I opened nvim and ran `:PackerSync`.

Next time I opened nvim I saw 
```
Error detected while processing VimEnter Autocommands for "*":
E492: Not an editor command: Dashboard
```

**Comment by artart222** [comment]
run `:PackerCompile` inside NeoVim

**Comment by artart222** [comment]
If after that you have problem please reopen problem

**Comment by rossvz** [comment]
```
[packer.nvim] [ERROR 10:17:03] async.lua:20: Error in coroutine: ...e/nvim/site...ot an editor command: -- Automatically generated packer.nvim plugin loader code
```

**Comment by artart222** [comment]
Run `:PackerSync` inside NeoVim and reload NeoVim

**Comment by rossvz** [comment]
Yeah, tried that. Looks like `PackerSync` has everything up to date

**Comment by artart222** [comment]
I will look at your problem and answer in 2 hours. I must do my school homework -_-

**Comment by artart222** [comment]
I looked at your at your problem I can't figure out why this is happening and also I don't have device with macOS so the code is not tested on mac. I will be happy if you can fix the problem and commit the solution

**Comment by Israel-Laguan** [comment]
Can confirm this on Mac Catalina
![image](https://user-images.githubusercontent.com/36519478/140684534-1f548cf4-c6e0-4121-aaca-7e40f1038fae.png)

**Comment by artart222** [comment]
DId you ran `:PackerSync` after installation?

**Comment by Israel-Laguan** [comment]
I solved by

```sh
# run nvim
:PackerCompile
:q! # Exit
# run nvim
:PackerSync
:q!
# run nvim
```

Like this to works now
![image](https://user-images.githubusercontent.com/36519478/140684894-918ea7b9-2216-4a5b-8a13-e48cc5e9046d.png)

@rossvz please try this

**Comment by sunghyouk** [comment]
> I solved by
> 
> ```shell
> # run nvim
> :PackerCompile
> :q! # Exit
> # run nvim
> :PackerSync
> :q!
> # run nvim
> ```
> 
> Like this it works now 😀 ![image](https://user-images.githubusercontent.com/36519478/140684894-918ea7b9-2216-4a5b-8a13-e48cc5e9046d.png)
> 
> @rossvz please try this

I'm a MacBook user, and it's a bit complicated as I have several python2 and 3 installed including anaconda on my computer. 
However, I want to use this setting, so I often come to see the issue of whether it is difficult to install on a Mac.

Are the screenshots above intended?
I would appreciate it if you could give me a final screenshot of the installation or a review.

**Comment by Israel-Laguan** [comment]
The installation succeeded without more issues from my side @sunghyouk. The screenshot blueish color is because the terminal theme I had, let me share a quick video opening vim on iTerm2:

https://user-images.githubusercontent.com/36519478/141226906-1b96ba3e-59f0-47ed-9d86-439542ad02e0.mp4

After install I just added TS support and it looks like that. Please try on your Mac and report how it goes.

**Comment by sunghyouk** [comment]
Thanks to @Israel-Laguan.
The install process was completed with `brew uninstall neovim` and `install`, although `cmake` gave an error while installing nvim from homebrew.

After `PackerInstall` - `PackerCompile` and `PackerSync` as instructed, it worked fine.
When I did `:checkhealth` I have a few questions to ask.

1) I am ignorant of `lua`. In the old `init.vim`, I wrote the path of `python3` to `let g:python3_host_prog`, Where can I get these settings?

2) I don't know if this is intended, but when I change the colorscheme in `telescope`, quit neovim and restart it, it is set to default. Where can I change this setting?

3) All of this may be because I couldn't find the config file, as shown in the screenshot below. How do I fix this?
<img width="590" alt="스크린샷 2021-11-11 오후 2 22 46" src="https://user-images.githubusercontent.com/89435559/141242162-c7006495-9afe-45ea-b048-7a91de136eb7.png">

4) Not always, but sometimes `telescope` doesn't work, including find file.

Thanks @artart222, @Israel-Laguan

**Comment by artart222** [comment]
For changing colorscheme and not loose it when closing CodeArt you can add vim.cmd("your_colorscheme") to ~/.config/nvim/lua/user_settings.lua

**Comment by artart222** [comment]
I look at checkhealth problem. I fixed one of errors but others seems not related to CodeArt and related to CodeArt plugins

**Comment by dhairy-online** [comment]
> I solved by
> 
> ```shell
> # run nvim
> :PackerCompile
> :q! # Exit
> # run nvim
> :PackerSync
> :q!
> # run nvim
> ```
> 
> Like this it works now grinning ![image](https://user-images.githubusercontent.com/36519478/140684894-918ea7b9-2216-4a5b-8a13-e48cc5e9046d.png)
> 
> @rossvz please try this

This worked for me, thanks!
