### ISSUE TITLE
Your install script does too much

### ISSUE THREAD

**Issue by mgutz** [artart222/CodeArt#55]
I didn't realize how much this installs. Your installer replaced node and other utilities at the system level! If someone is enough of a power user to use nvim, they can install dependencies manually. I thought your installer would just bootstrap packer like other nvim distros.

**Comment by artart222** [comment]
Yes my install script does to much and I understand your point but I prefer to not change install script. I made this distro to make working with neovim easier for absolute beginners and because of that Installer is like that and my distro is bloated with builtin debugger and other stuff.

**Comment by SonicZentropy** [comment]
Sorry to reopen this, but some sort of warning in the Readme would be extremely nice on this one.  This just torched my system, and I realize it's on me for mashing OK instead of reading every line, but changing system packages is a pretty unexpected "feature" of a text editor customization script.  Nowhere in there does it even hint at the fact that CodeArt is about to have its way with your system
